# Generated by Django 5.0.3 on 2024-03-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_member_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('pass_word', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(default='Write Student / Teacher', max_length=50),
        ),
    ]
