# Generated by Django 5.0.3 on 2024-03-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Full Course', 'Full Course'), ('crash Course', 'crash Course')], max_length=200, null=True)),
                ('host', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200, null=True)),
                ('experience', models.CharField(max_length=3, null=True)),
                ('length', models.CharField(choices=[('45', '45'), ('60', '60'), ('90', '90')], max_length=200, null=True)),
                ('timing_start', models.CharField(max_length=2, null=True)),
                ('timing_end', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
