# Generated by Django 5.0.3 on 2024-03-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_tag_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
