# Generated by Django 5.0.3 on 2024-03-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='experience',
            field=models.IntegerField(null=True),
        ),
    ]
